### ISSUE TITLE
Frame Count

### ISSUE THREAD

**Issue by dustpg** [shobomaru/HelloD3D12#1]
Hello Shobomaru!
   I think the frame count should be initialized to 1. if to 0, it will trigger "D2D12 ERROR" in 2nd-time rendering. 
   BTW, is there a way to get IDXGIDeviceN interface? I tried to call ID3D12Device::QueryInterface to query, but return E_NOINTERFACE _(:3」∠)_
   Thanks.

**Comment by shobomaru** [comment]
Hello Dustpg.

> I think the frame count should be initialized to 1. if to 0, it will trigger "D2D12 ERROR" in 2nd-time rendering.

To tell the truth, I don't understand much about Command Queue and Fence.
I'll examine again and fix it.

> BTW, is there a way to get IDXGIDeviceN interface? I tried to call ID3D12Device::QueryInterface to query, but return E_NOINTERFACE _(:3」∠)_

Me too (´・ω・`)
As far as I know, nobody could succeed to create IDXGIDevice using QueryInterface on Windows 10.
I doubt whether MSDN document is right.

Thank you!

**Comment by dustpg** [comment]
thanks
